### ISSUE TITLE
Minor issues in Pop-Up-Shop.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#1]
- Text says demand is 400 for good weather, code says 350.
- Text says unit cost is 5, code says 12.
- The probabilities of the three scenarios are also inconsistent between text and code.
- `TypeError: unsupported format string passed to NoneType.__format__ `
- `ERROR: evaluating object as numeric value: f[sunny skies] (object: <class 'pyomo.core.base.var._GeneralVarData'>) No value for uninitialized NumericValue object f[sunny skies]`
- Do we want the glpsol script?

**Comment by jckantor** [comment]
The notebook has been updated, all cells now run correctly and the narrative is complete. Let me know if  further edits are warranted. I'll close the issue for now.
