### ISSUE TITLE
Lingering issues in mad-portfolio-optimization.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#13]
Lingering issues in [mad-portfolio-optimization.ipynb](https://github.com/jckantor/MO-book/blob/main/notebooks/02/mad-portfolio-optimization.ipynb):

- [x] missing extensive mathematical formulation of the optimization problem (at least early on in the notebook)
- [x] the statistical analysis of the historical data should be signalled better with a dedicated section
- [x] lots of incomplete/missing textual cells, especially to comment statistics
- [x] some of the code cells still contains bugs/errors and/or don't run properly
- [x] a lot of code/cells might be obsolete (like the pulp model) or not relevant or simply out of place? Please check
- [x] possibly related to the previous point, the notebook seem very long and too complex?
- [x] add narrative on risk vs return
- [x] add explanation for $T$ and $J$. In the book I added the following sentence: "Assume that we can make investment decisions at every trading day $t$ over a fixed time horizon ranging from $t=1,\dots,T$ and that there is a set of $J$ assets in which we can choose to invest."
- [x] Due to the absolute values, as it is written now in the notebook, $MAD$ is not the sum over $j$ of the $MAD_j$. This does not matter for the book, but maybe it'd be good to make the exposition crystal clear in the notebook.

**Comment by jckantor** [comment]
I've significantly rewritten the notebook.  I've placed the math "just in time" above the code cells where the it is put to work. Let me know what you think ... would it better to put the math all at the top?  

There may be some minor narrative additions near the end of teh notebook, but that shouldn't affect what you would need for the book.  I'll keep this issue open in the meanwhile.

**Comment by alessandrozocca** [comment]
This example has now been fully ported into the book. I have found a few more issues, which are listed above.

**Comment by jckantor** [comment]
The narrative is now much better, thanks for the feedback.
