### ISSUE TITLE
Chapter 2 notebooks

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#2]
The file /notebooks/02/EF_RO.ipynb should be move to a later chapter (being about robust optimization)

In the file /notebooks/02/02.02-MAD-Portfolio-Optimization.ipynb 

- [x] there is a wrong reference to pulp. `fixed`
- [x] there is a weird cite <ref>{{...}}</ref> environment which doesn't display correctly
- [x] there is cross-reference [[w: ... ]] which doesn't work

**Comment by alessandrozocca** [comment]
Can this be closed, @jckantor?

**Comment by jckantor** [comment]
This can be closed.
