### ISSUE TITLE
Lingering issues in Shift-Scheduling.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#20]
Lingering issues in [Shift-Scheduling.ipynb](https://github.com/jckantor/MO-book/blob/main/notebooks/03/Shift-Scheduling.ipynb):

- [x] Typo "perferences"
- [x] Typos "Inicator if worker has been assigned a weekend shift."
- [x] Incomplete sentence "This is formulated here as an objec"
- [x] gamma variable not displayed correctly
- [x] is there a way to report the solution as a pandas dataframe? (low priority)
- [ ] There are some rendering issues in some of the formulas in the model constraints section

**Comment by jckantor** [comment]
All fixed. Thanks for the check.

**Comment by alessandrozocca** [comment]
Reopened for two minor issues.

**Comment by jckantor** [comment]
Good catch on the gamma.  And a good suggestion regarding pandas.  I dropped the current section on reporting and replaced it with one based on Pandas. Much better, both didactically and value add for the book.

**Comment by alessandrozocca** [comment]
Reopened for a minor issue, see above.

**Comment by jckantor** [comment]
Ouch .. that looked ugly.  Should be fixed now.
