### ISSUE TITLE
Lingering issues in recharging-electric-vehicle.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#21]
Lingering issues in [recharging-electric-vehicle.ipynb](https://github.com/jckantor/MO-book/blob/main/notebooks/03/recharging-electric-vehicle.ipynb)

- [x] Sentence "The distances to the charging stations are measured relative to an arbitrary location." should be the 2nd and not the 1st one?

**Comment by jckantor** [comment]
Thanks again.  Here's the new wording "Given the current location  𝑥 , battery charge  𝑐 , and planning horizon  𝐷 , the task is to plan a series of recharging and rest stops. Data is provided for the location and the charging rate available at each charging stations. The objective is to drive from location  𝑥  to location  𝑥+𝐷  in as little time as possible subject to the following constraints:"

**Comment by jckantor** [comment]
Also fixed up the visuals a bit.
