### ISSUE TITLE
Change `pyomo.xxx` to `pyo.xxx` in style guide

### ISSUE THREAD

**Issue by leonlan** [jckantor/MO-book#4]
Hi Jeffrey,

Great style guide on pyomo, I love it!

One additional and small suggestion is to change references of `pyomo.Var`, `pyomo.Constraint`, etc. to `pyo.Var` and `pyo.Constraint` to stick to the namespace convention.

Best,
Leon

**Comment by jckantor** [comment]
Thanks, Leon.  Much appreciated.

I wrestled with `pyomo.xxx` versus `pyo.xxx` for some time.  I used `pyomo.xxx` to be sure there was no ambiguity. But I think you're right on this one, and will make the changes.  Thanks for the typo checking, too, those changes are now merged into the main branch.
