### ISSUE TITLE
Colab code inside every notebook?

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#5]
Every page of the book can be run in google colab with a simple click, so the code below (taken from the Pop Up Shop example) is extremely useful to make the notebook "runnable". However, is there a way to hide this or avoid it "interrupts" the story flow?

```
import sys
at_colab = "google.colab" in sys.modules

if at_colab:
    _=!pip install -q pyomo
    _=!wget -N -q "https://ampl.com/dl/open/ipopt/ipopt-linux64.zip"
    _=!unzip -o -q ipopt-linux64
    _=!apt-get install -y -q coinor-cbc
    _=!pip install -q cplex
    _=!pip install -q gurobipy
    _=!pip install -q xpress
```

**Comment by jckantor** [comment]
I've updated this to use the asyncio library, which speeds up the downloads and install. I've fixed a problem with installing gecode solver.  I'm going to close this, but glad to reopen if there's any cleanup needed.
