### ISSUE TITLE
Lingering issues in fit-absolute.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#8]
Lingering issues in [fit-absolute.ipynb](https://github.com/jckantor/MO-book/blob/main/notebooks/02/fit-absolute.ipynb):

- [x] add to the current explanatory/introductory text the various paragraps and equations that I wrote in the book (see Example 2)?
- [x] change title to "Least Absolute Deviation Regression" to make it consistent with the book?
- [x] change m = pyo.ConcreteModel('min abs') into m = pyo.ConcreteModel('LAD regression')
- [x] consolidate the whole Pyomo model in a single cell?
- [x] add one or two text cells to comment data generation and data visualization?
- [x]  The domains of the variables X and y are displayed as \mathcal{R}, but they should be \mathbb{R}
- [x] The sentence "we can use the trick illustrated above to transform it into a linear problem" is appropriate for the book, but not for the companion notebook.

**Comment by jckantor** [comment]
I changed the name of the file to lad-regression to reflect the new title and additional content. I cut and pasted the example text from the book, with some edits for markdown.  I added a histogram of residuals to provide some visualization for the multivariable case.  Should be ready to close.

**Comment by jckantor** [comment]
Closing this one.  Feel free to reopen if there are issues.

**Comment by alessandrozocca** [comment]
- [ ] The domains of the variables X and y are displayed as \mathcal{R}, but they should be \mathbb{R}
- [ ] The sentence "we can use the trick illustrated above to transform it into a linear problem" is appropriate for the book, but not for the companion notebook.

**Comment by jckantor** [comment]
Good catches. I've fixed the math format issue, and replaced the problem sentence with "In general, the appearance of an absolute value term indicates the problem is nonlinear and, worse, that the objective function is not differentiable when any  𝑒𝑖=0 . However, for this case where the objective is to minimize a sum of absolute errors, one can reformulate the decision variables to transform this into a linear problem. "

**Comment by alessandrozocca** [comment]
Perfect, I close this now.
