### ISSUE TITLE
Lingering issues in Transportation.ipynb

### ISSUE THREAD

**Issue by alessandrozocca** [jckantor/MO-book#9]
Lingering issues in [Transportation.ipynb](https://github.com/jckantor/MO-book/blob/main/notebooks/02/Transportation.ipynb):

- [x] dollar signs are not rendered correctly in the text (cf. &dollar;)
- [x] we can stick to dollars and gallons, but maybe state somewhere that the franchise is based in the US?
- [x] is there another (more common?) word instead of incumbant?maybe my confusion arises because this is also never defined
- [x] mathematical model is never given explicitly and some textual cells could be added here and there to guide the reader
- [x] we are currently displaying the solution in 3 different ways, which may be unnecessary (unless there is something didactical about it, but then more text is needed)
- [x] story is too long? can we streamline it even more?

**Comment by jckantor** [comment]
I've clarified the didactic elements of the notebook, and expanded the modeling quite a bit to demonstrate model refinement and analysis. This turned out to be a bit longer than originally intended, but seemed like a good teaching opportunity.  Let me know what you think.

**Comment by jckantor** [comment]
I'm going to close this to indicate that it should be ready to go. Feel free to reopen if there are issues.

**Comment by alessandrozocca** [comment]
This notebook reads much more clearly, Jeff, thanks for all the added text and clarifications. I think it's very instructive, I'll try to find a way to port at least a fraction of it to the book!

One minor issue: in the table, the row with the totals has one number too many?

**Comment by alessandrozocca** [comment]
@jckantor I haven't fully ported this example yet into the book, so as long as the notebook is correct now, I'll take care of it later today.

**Comment by jckantor** [comment]
I moved this notebook over to chapter 4 to be consistent with the book.
